name: NodeJS with Grunt (example)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Node v            # Node v 확인
      run: node -v

    - name: Build
      run: |
        pnpm run dev
